using System.Collections.Generic;

public static class Waypoints
{
    public static readonly Dictionary<string, string> Codes = new Dictionary<string, string>()
    {
        // Ascalon.
        // Blazeridge Steppes.
        { "[&BPkBAAA=]", "The Last Whiskey Bar Waypoint" },
        { "[&BPoBAAA=]", "Steeleye Waypoint" },
        { "[&BPsBAAA=]", "Tumok's Waypoint" },
        { "[&BPwBAAA=]", "Twin Sisters Waypoint" },
        { "[&BP0BAAA=]", "Behem Waypoint" },
        { "[&BP4BAAA=]", "Expanse Waypoint" },
        { "[&BP8BAAA=]", "Guardian Stone Waypoint" },
        { "[&BAACAAA=]", "Lunk Kraal Waypoint" },
        { "[&BAECAAA=]", "Terra Carorunda Waypoint" },
        { "[&BAICAAA=]", "Brokentooth Waypoint" },
        { "[&BAMCAAA=]", "Kindling Waypoint" },
        { "[&BAQCAAA=]", "Brandview Waypoint" },
        { "[&BAUCAAA=]", "Refuge Sanctum Waypoint" },
        { "[&BE4DAAA=]", "Lowland Burns Waypoint" },
        { "[&BE8DAAA=]", "Gastor Gullet Waypoint" },
        { "[&BFADAAA=]", "Kinar Fort Waypoint" },
        { "[&BFEDAAA=]", "Splintercrest Fort Waypoint" },
        { "[&BFIDAAA=]", "Soot Road Waypoint" },

        // Diessa Plateau.
        { "[&BNkAAAA=]", "Charrgate Haven Waypoint" },
        { "[&BNoAAAA=]", "Blasted Moors Waypoint" },
        { "[&BNsAAAA=]", "Bloodsaw Mill Waypoint" },
        { "[&BNwAAAA=]", "Font of Rhand Waypoint" },
        { "[&BN0AAAA=]", "Nageling Waypoint" },
        { "[&BN4AAAA=]", "Nolan Waypoint" },
        { "[&BF4BAAA=]", "Oldgate Waypoint" },
        { "[&BF8BAAA=]", "Butcher's Block Waypoint" },
        { "[&BGABAAA=]", "Charradis Estate Waypoint" },
        { "[&BGEBAAA=]", "Breached Wall Waypoint" },
        { "[&BGIBAAA=]", "Incendio Waypoint" },
        { "[&BGMBAAA=]", "Nemus Grove Waypoint" },
        { "[&BGQBAAA=]", "Breachwater Waypoint" },
        { "[&BJoDAAA=]", "Dawnright Estate Waypoint" },
        { "[&BMQDAAA=]", "Bloodcliff Waypoint" },
        { "[&BMUDAAA=]", "Sanctum Waypoint" },
        { "[&BMYDAAA=]", "Redreave Mill Waypoint" },
        { "[&BMkDAAA=]", "Manbane's Waypoint" },
        { "[&BEIEAAA=]", "Blackblade Waypoint" },

        // Fields of Ruin.
        { "[&BNMAAAA=]", "Hawkgates Waypoint" },
        { "[&BNQAAAA=]", "Deathblade's Watch Waypoint" },
        { "[&BNUAAAA=]", "Summit Waypoint" },
        { "[&BNYAAAA=]", "Tyler's Bivouac Waypoint" },
        { "[&BNcAAAA=]", "Tenaebron Waypoint" },
        { "[&BNgAAAA=]", "Rosko's Campsite Waypoint" },
        { "[&BEoBAAA=]", "Skoll's Bivouac Waypoint" },
        { "[&BEsBAAA=]", "Helliot Mine Waypoint" },
        { "[&BEwBAAA=]", "Fangfury Watch Waypoint" },
        { "[&BE0BAAA=]", "Vulture's Waypoint" },
        { "[&BE4BAAA=]", "Wreckage of Bloodgorge Watch Waypoint" },
        { "[&BE8BAAA=]", "Ogre Road Waypoint" },
        { "[&BFABAAA=]", "Forlorn Gate Waypoint" },
        { "[&BFEBAAA=]", "Fallen Angels Garrison Waypoint" },
        { "[&BDwEAAA=]", "Spotter's Waypoint" },
        { "[&BD0EAAA=]", "Kestrel Waypoint" },
        { "[&BD4EAAA=]", "Thunderbreak Waypoint" },

        // Fireheart Rise.
        { "[&BBYCAAA=]", "Sati Waypoint" },
        { "[&BBcCAAA=]", "Pig Iron Waypoint" },
        { "[&BBgCAAA=]", "Tuyere Command Post Waypoint" },
        { "[&BBkCAAA=]", "Severed Breach Waypoint" },
        { "[&BBoCAAA=]", "Breaktooth's Waypoint" },
        { "[&BBsCAAA=]", "Havoc Waypoint" },
        { "[&BBwCAAA=]", "Vidius Castrum Waypoint" },
        { "[&BB0CAAA=]", "Apostate Waypoint" },
        { "[&BB4CAAA=]", "Rustbowl Waypoint" },
        { "[&BB8CAAA=]", "Switchback Waypoint" },
        { "[&BCACAAA=]", "Icespear's Waypoint" },
        { "[&BCECAAA=]", "Snow Ridge Camp Waypoint" },
        { "[&BCICAAA=]", "Vorgas Garrison Waypoint" },
        { "[&BCMCAAA=]", "Forlorn Waypoint" },
        { "[&BCQCAAA=]", "Senecus Castrum Waypoint" },
        { "[&BCUCAAA=]", "Simurgh Waypoint" },
        { "[&BCYCAAA=]", "Keeper's Waypoint" },
        { "[&BEAFAAA=]", "The Flame Citadel Waypoint" },

        // Iron Marches.
        { "[&BOIBAAA=]", "Dewclaw Waypoint" },
        { "[&BOMBAAA=]", "Bloodfin Lake Waypoint" },
        { "[&BOQBAAA=]", "Old Piken Ruins Waypoint" },
        { "[&BOUBAAA=]", "Warhound Village Waypoint" },
        { "[&BOYBAAA=]", "Hellion Waypoint" },
        { "[&BOcBAAA=]", "Village of Scalecatch Waypoint" },
        { "[&BOgBAAA=]", "Sleekfur Encampment Waypoint" },
        { "[&BOkBAAA=]", "Brandwatch Encampment Waypoint" },
        { "[&BOoBAAA=]", "Viper's Run Waypoint" },
        { "[&BOsBAAA=]", "Town of Cowlfang's Star Waypoint" },
        { "[&BOwBAAA=]", "Bulwark Waypoint" },
        { "[&BO0BAAA=]", "Firewatch Encampment Waypoint" },
        { "[&BO4BAAA=]", "Gladefall Waypoint" },
        { "[&BO8BAAA=]", "Grostogg's Kraal Waypoint " },

        // Plains of Ashford.
        { "[&BH8BAAA=]", "Vir's Gate Waypoint" },
        { "[&BIABAAA=]", "Smokestead Waypoint" },
        { "[&BIEBAAA=]", "Greysteel Armory Waypoint" },
        { "[&BIIBAAA=]", "Martyr's Waypoint" },
        { "[&BIMBAAA=]", "Temperus Point Waypoint" },
        { "[&BIQBAAA=]", "Ashford Waypoint" },
        { "[&BIUBAAA=]", "Adorea Waypoint" },
        { "[&BIYBAAA=]", "Ascalonian Catacombs Waypoint" },
        { "[&BIcBAAA=]", "Ascalon City Waypoint" },
        { "[&BIgBAAA=]", "Watchcrag Tower Waypoint" },
        { "[&BIkBAAA=]", "Duskrend Overlook Waypoint" },
        { "[&BIoBAAA=]", "Irondock Shipyard Waypoint" },
        { "[&BJcDAAA=]", "Feritas Waypoint" },
        { "[&BJgDAAA=]", "Guardpoint Decimus Waypoint" },
        { "[&BJkDAAA=]", "Spirit Hunter Camp Waypoint" },
        { "[&BMcDAAA=]", "Loreclaw Waypoint" },
        { "[&BMgDAAA=]", "Phasmatis Waypoint" },
        { "[&BPgGAAA=]", "Langmar Estate Waypoint" },

        // Heart of Maguuma.
        // Verdant Brink.
        { "[&BMAHAAA=]", "Shipwreck Peak Waypoint" },
        { "[&BNUHAAA=]", "Mellaggan's Valor Waypoint" },
        { "[&BN4HAAA=]", "Shipwreck Peak Waypoint" },
        { "[&BOAHAAA=]", "Jaka Itzel Waypoint" },
        { "[&BO8HAAA=]", "Faren's Flyer Waypoint" },
        { "[&BAEIAAA=]", "Shrouded Ruins Waypoint" },
        { "[&BAgIAAA=]", "Pact Encampment Waypoint" },
        { "[&BBwIAAA=]", "Treacherous Path Waypoint" },

        // Auric Basin.
        { "[&BMYHAAA=]", "Forgotten City Waypoint" },
        { "[&BNYHAAA=]", "Wanderer's Waypoint" },
        { "[&BN0HAAA=]", "Northwatch Waypoint" },
        { "[&BAIIAAA=]", "Southwatch Waypoint" },
        { "[&BAYIAAA=]", "Westwatch Waypoint" },
        { "[&BEkIAAA=]", "Chak Hollow Waypoint" },
        { "[&BGwIAAA=]", "Eastwatch Waypoint" },

        // Tangled Depths.
        { "[&BMwHAAA=]", "Ogre Camp Waypoint" },
        { "[&BPUHAAA=]", "Ley-Line Confluence Waypoint" },
        { "[&BAAIAAA=]", "SCAR Camp Waypoint" },
        { "[&BAMIAAA=]", "Rata Novus Waypoint" },
        { "[&BAwIAAA=]", "Teku Nuhoch Waypoint" },
        { "[&BA4IAAA=]", "Order of Whispers Camp Waypoint" },
        { "[&BIgIAAA=]", "Dragon's Passage Waypoint " },

        // Dragon's Stand.
        { "[&BBAIAAA=]", "Pact Base Camp Waypoint" },
        { "[&BC4IAAA=]", "Central Forward Camp Waypoint" },
        { "[&BE8IAAA=]", "Southern Forward Camp Waypoint" },
        { "[&BFIIAAA=]", "Northern Forward Camp Waypoint" },
        { "[&BFMIAAA=]", "Central Advance Camp Waypoint" },
        { "[&BFcIAAA=]", "Dragon's Domain Southern Waypoint" },
        { "[&BGUIAAA=]", "Southern Advance Camp Waypoint" },
        { "[&BHoIAAA=]", "Pact Base Camp Southern Waypoint" },
        { "[&BJcIAAA=]", "Dragon's Domain Central Waypoint" },
        { "[&BK4IAAA=]", "Dragon's Domain Northern Waypoint" },
        { "[&BAAJAAA=]", "Northern Advance Camp Waypoint" },

        // Bloodstone Fen.
        { "[&BD8JAAA=]", "Depths of the Maw Waypoint" },
        { "[&BEEJAAA=]", "Ground Zero Waypoint" },
        { "[&BEsJAAA=]", "Soulkeeper's Airship Waypoint" },
        { "[&BE4JAAA=]", "Zealot's Overlook Waypoint " },

        // Kryta.
        // Bloodtide Coast.
        { "[&BKMBAAA=]", "Archen Foreland Waypoint" },
        { "[&BKQBAAA=]", "Sorrowful Waypoint" },
        { "[&BKUBAAA=]", "Stormbluff Waypoint" },
        { "[&BKYBAAA=]", "Marshwatch Haven Waypoint" },
        { "[&BKcBAAA=]", "Remanda Waypoint" },
        { "[&BKgBAAA=]", "Laughing Gull Waypoint" },
        { "[&BKkBAAA=]", "Barrier Camp Waypoint" },
        { "[&BKoBAAA=]", "Firthside Vigil Waypoint" },
        { "[&BKsBAAA=]", "Lostwreck Waypoint" },
        { "[&BKwBAAA=]", "Bogside Camp Waypoint" },
        { "[&BK0BAAA=]", "Mournful Waypoint" },
        { "[&BK4BAAA=]", "Castavall Waypoint" },
        { "[&BK8BAAA=]", "Jelako Waypoint" },
        { "[&BLABAAA=]", "Whisperwill Waypoint" },
        { "[&BAsEAAA=]", "Deadend Waypoint" },

        // Gendarran Fields.
        { "[&BN8AAAA=]", "Traveler's Dale Waypoint" },
        { "[&BOAAAAA=]", "Stoneguard Gate Waypoint" },
        { "[&BOEAAAA=]", "Broadhollow Waypoint" },
        { "[&BOIAAAA=]", "Oogooth Waypoint" },
        { "[&BOMAAAA=]", "Cornucopian Fields Waypoint" },
        { "[&BOQAAAA=]", "Provern Shore Waypoint" },
        { "[&BO0AAAA=]", "Junction Haven Waypoint" },
        { "[&BO4AAAA=]", "Winter Haven Waypoint" },
        { "[&BIsBAAA=]", "First Haven Waypoint" },
        { "[&BIwBAAA=]", "Talajian Waypoint" },
        { "[&BI0BAAA=]", "Blood Hill Waypoint" },
        { "[&BI4BAAA=]", "Nebo Terrace Waypoint" },
        { "[&BI8BAAA=]", "Ascalon Settlement Waypoint" },
        { "[&BJABAAA=]", "Northfields Waypoint" },
        { "[&BJEBAAA=]", "Applenook Hamlet Waypoint" },
        { "[&BJIBAAA=]", "Vigil Keep Waypoint" },
        { "[&BJMBAAA=]", "Icegate Waypoint" },
        { "[&BJQBAAA=]", "Almuten Waypoint" },
        { "[&BJsDAAA=]", "Lionbridge Waypoint" },
        { "[&BMwDAAA=]", "Snowblind Waypoint" },
        { "[&BM0DAAA=]", "Brigantine Waypoint" },
        { "[&BAIEAAA=]", "Bloodfields Waypoint" },

        // Harthi Hinterlands.
        { "[&BKUAAAA=]", "Faun's Waypoint" },
        { "[&BKYAAAA=]", "Shieldbluff Waypoint" },
        { "[&BKcAAAA=]", "Seraph's Landing Waypoint" },
        { "[&BKgAAAA=]", "Wynchona Rally Point Waypoint" },
        { "[&BKkAAAA=]", "Grey Gritta's Waypoint" },
        { "[&BKoAAAA=]", "Nightguard Waypoint" },
        { "[&BKsAAAA=]", "Demetra Waypoint" },
        { "[&BKwAAAA=]", "Recovery Camp Waypoint" },
        { "[&BK0AAAA=]", "Barricade Camp Waypoint" },
        { "[&BK4AAAA=]", "Trebusha's Overlook Waypoint" },
        { "[&BK8AAAA=]", "Bridgewatch Camp Waypoint" },
        { "[&BLAAAAA=]", "Junction Camp Waypoint" },
        { "[&BLEAAAA=]", "Cloven Hoof Waypoint" },
        { "[&BLIAAAA=]", "Arca Waypoint" },
        { "[&BMMAAAA=]", "Arcallion Waypoint" },

        // Kessex Hills.
        { "[&BAMAAAA=]", "Fort Salma Waypoint" },
        { "[&BAQAAAA=]", "Overlord's Waypoint" },
        { "[&BAYAAAA=]", "Halacon Waypoint" },
        { "[&BAcAAAA=]", "Sojourner's Waypoint" },
        { "[&BAgAAAA=]", "Delanian Waypoint" },
        { "[&BAoAAAA=]", "Ireko Tradecamp Waypoint" },
        { "[&BAwAAAA=]", "Shadowheart Site Waypoint" },
        { "[&BBAAAAA=]", "Viathan Waypoint" },
        { "[&BBEAAAA=]", "Darkwound Waypoint" },
        { "[&BBIAAAA=]", "Cereboth Waypoint" },
        { "[&BBMAAAA=]", "Overlake Haven Waypoint" },
        { "[&BBQAAAA=]", "Kessex Haven Waypoint" },
        { "[&BBUAAAA=]", "Cavernhold Camp Waypoint" },
        { "[&BBYAAAA=]", "Greyhoof Camp Waypoint" },
        { "[&BLkDAAA=]", "Earthworks Camp Waypoint" },
        { "[&BLoDAAA=]", "Gap Waypoint" },

        // Queensdale.
        { "[&BO8AAAA=]", "Shaemoor Waypoint" },
        { "[&BPAAAAA=]", "Fields Waypoint" },
        { "[&BPEAAAA=]", "Garrison Waypoint" },
        { "[&BPIAAAA=]", "Crossing Waypoint" },
        { "[&BPMAAAA=]", "Phinney Waypoint" },
        { "[&BPQAAAA=]", "Vale Waypoint" },
        { "[&BPUAAAA=]", "Heartwood Pass Camp Waypoint" },
        { "[&BPYAAAA=]", "Claypool Waypoint" },
        { "[&BPcAAAA=]", "Swamplost Haven Waypoint" },
        { "[&BPgAAAA=]", "Krytan Waypoint" },
        { "[&BPkAAAA=]", "Ojon's Lumbermill Waypoint" },
        { "[&BPoAAAA=]", "Beetletun Waypoint" },
        { "[&BPsAAAA=]", "Tunwatch Redoubt Waypoint" },
        { "[&BPwAAAA=]", "Godslost Waypoint" },
        { "[&BEQDAAA=]", "Orchard Waypoint" },
        { "[&BEUDAAA=]", "Scaver Waypoint" },

        // Maguuma Jungle.
        // Brisban Wildlands.
        { "[&BFwAAAA=]", "Watchful Source Waypoint" },
        { "[&BF0AAAA=]", "Wendon Waypoint" },
        { "[&BF4AAAA=]", "Tunnels Waypoint" },
        { "[&BF8AAAA=]", "Hillstead Waypoint" },
        { "[&BGAAAAA=]", "East End Waypoint" },
        { "[&BGEAAAA=]", "Brilitine Waypoint" },
        { "[&BGIAAAA=]", "Seraph Observers Waypoint" },
        { "[&BGMAAAA=]", "Gallowfields Waypoint" },
        { "[&BGQAAAA=]", "Triforge Point Waypoint" },
        { "[&BGUAAAA=]", "Ulta Metamagicals Waypoint" },
        { "[&BHUAAAA=]", "Mrot Boru Waypoint" },
        { "[&BHYAAAA=]", "Mirkrise Waypoint" },
        { "[&BPkGAAA=]", "Proxemics Lab Waypoint" },

        // Caledon Forest.
        { "[&BDQBAAA=]", "Astorea Waypoint" },
        { "[&BDUBAAA=]", "Spiral Waypoint" },
        { "[&BDYBAAA=]", "Caer Astorea Waypoint" },
        { "[&BDcBAAA=]", "Gleaner's Cove Waypoint" },
        { "[&BDgBAAA=]", "Brigid's Overlook Waypoint" },
        { "[&BDkBAAA=]", "Sperrins Waypoint" },
        { "[&BDoBAAA=]", "Mabon Waypoint" },
        { "[&BDsBAAA=]", "Town of Cathal Waypoint" },
        { "[&BDwBAAA=]", "Caledon Haven Waypoint" },
        { "[&BD0BAAA=]", "Titan's Staircase Waypoint" },
        { "[&BD4BAAA=]", "Falias Thorp Waypoint" },
        { "[&BD8BAAA=]", "Hamlet of Annwen Waypoint" },
        { "[&BEABAAA=]", "Kraitbane Haven Waypoint" },
        { "[&BEEBAAA=]", "Wychmire Waypoint" },
        { "[&BEIBAAA=]", "Wardenhurst Waypoint" },
        { "[&BEwDAAA=]", "Lionguard Waystation Waypoint" },
        { "[&BEEFAAA=]", "Twilight Arbor Waypoint" },
        { "[&BP4FAAA=]", "Sleive's Waypoint " },

        // Metrica Province.
        { "[&BEAAAAA=]", "Soren Draa Waypoint" },
        { "[&BEEAAAA=]", "Jeztar Falls Waypoint" },
        { "[&BEIAAAA=]", "Akk Wilds Waypoint" },
        { "[&BEMAAAA=]", "Rana Landing Complex Waypoint" },
        { "[&BEQAAAA=]", "Arterium Haven Waypoint" },
        { "[&BEUAAAA=]", "Hexane Regrade Waypoint" },
        { "[&BEYAAAA=]", "Survivor's Encampment Waypoint" },
        { "[&BEcAAAA=]", "Muridian Waypoint" },
        { "[&BEgAAAA=]", "Desider Atum Waypoint" },
        { "[&BK4EAAA=]", "Old Golem Factory Waypoint" },
        { "[&BK8EAAA=]", "Loch Waypoint" },
        { "[&BLAEAAA=]", "Anthill Waypoint" },
        { "[&BLEEAAA=]", "Michotl Grounds Waypoint" },
        { "[&BLIEAAA=]", "Cuatl Waypoint" },
        { "[&BLMEAAA=]", "Artergon Waypoint" },
        { "[&BPcEAAA=]", "Hydrone Unit Waypoint" },

        // Mount Maelstrom.
        { "[&BMcCAAA=]", "Murkvale Waypoint" },
        { "[&BMgCAAA=]", "Govoran Waypoint" },
        { "[&BMkCAAA=]", "Criterion Waypoint" },
        { "[&BMoCAAA=]", "Firebreak Fort Waypoint" },
        { "[&BMsCAAA=]", "Spaecia Illogica Waypoint" },
        { "[&BMwCAAA=]", "Bard's Waypoint" },
        { "[&BM0CAAA=]", "Maelstrom's Waypoint" },
        { "[&BM4CAAA=]", "Ashen Waypoint" },
        { "[&BM8CAAA=]", "Avernan Waypoint" },
        { "[&BNACAAA=]", "Broken Arrow Waypoint" },
        { "[&BNECAAA=]", "Oxbow Isle Waypoint" },
        { "[&BNICAAA=]", "Irwin Isle Waypoint" },
        { "[&BNMCAAA=]", "Gauntlet Waypoint" },
        { "[&BNQCAAA=]", "Old Sledge Site Waypoint" },
        { "[&BNUCAAA=]", "Judgment Waypoint" },
        { "[&BNYCAAA=]", "Magmatic Waypoint" },
        { "[&BEIFAAA=]", "Crucible of Eternity Waypoint" },

        // Sparkfly Fen.
        { "[&BMQBAAA=]", "Orvar's Glen Waypoint" },
        { "[&BMUBAAA=]", "Fort Cadence Waypoint" },
        { "[&BMYBAAA=]", "Braggi's Stead Waypoint" },
        { "[&BMcBAAA=]", "Saltflood Waypoint" },
        { "[&BMgBAAA=]", "Zintl Holy Grounds Waypoint" },
        { "[&BMkBAAA=]", "Ocean's Gullet Waypoint" },
        { "[&BMoBAAA=]", "Forvar's Waypoint" },
        { "[&BMsBAAA=]", "Toade's Head Waypoint" },
        { "[&BMwBAAA=]", "Flamefrog Waypoint" },
        { "[&BM0BAAA=]", "Darkweather Waypoint" },
        { "[&BM4BAAA=]", "Brackwater Waypoint" },
        { "[&BM8BAAA=]", "Aleem's Waypoint" },
        { "[&BNABAAA=]", "Splintered Coast Waypoint" },
        { "[&BNEBAAA=]", "Brooloonu Waypoint" },
        { "[&BE0DAAA=]", "Dryground Village Waypoint" },
        { "[&BLMDAAA=]", "Caer Brier Waypoint" },
        { "[&BLQDAAA=]", "Mire Waypoint" },

        // Maguuma Wastes.
        // Dry Top.
        { "[&BHoHAAA=]", "Prosperity Waypoint" },
        { "[&BIAHAAA=]", "Dry Top Entry Waypoint" },
        { "[&BIYHAAA=]", "Vine Bridge Waypoint" },
        { "[&BIgHAAA=]", "Restoration Refuge Waypoint" },
        { "[&BJcHAAA=]", "Repair Station Waypoint" },

        // The Silverwastes.
        { "[&BH8HAAA=]", "Camp Resolve Waypoint" },
        { "[&BKwHAAA=]", "Hidden Depths Waypoint" },
        { "[&BLoHAAA=]", "Dry Dock Grotto Waypoint" },

        // Ring of Fire.
        // Ember Bay.
        { "[&BFUJAAA=]", "Scratch Gate Waypoint" },
        { "[&BF8JAAA=]", "Promontory Waypoint" },
        { "[&BGAJAAA=]", "Crumbling Trail Waypoint" },
        { "[&BHgJAAA=]", "Castaway Circus Waypoint" },

        // Ruins of Orr.
        // Cursed Shore.
        { "[&BBcDAAA=]", "Pursuit Pass Waypoint" },
        { "[&BBgDAAA=]", "R&D Waypoint" },
        { "[&BBkDAAA=]", "Penitent Waypoint" },
        { "[&BBoDAAA=]", "Gavbeorn's Waypoint" },
        { "[&BBsDAAA=]", "Verdance Waypoint" },
        { "[&BBwDAAA=]", "Shelter's Gate Waypoint" },
        { "[&BB0DAAA=]", "Jofast's Waypoint" },
        { "[&BB4DAAA=]", "Meddler's Waypoint" },
        { "[&BB8DAAA=]", "Anchorage Waypoint" },
        { "[&BCADAAA=]", "Arah Waypoint" },
        { "[&BCEDAAA=]", "Caer Shadowfain Waypoint" },
        { "[&BCIDAAA=]", "Murdered Dreams Waypoint" },
        { "[&BOQGAAA=]", "Shipwreck Rock Waypoint" },

        // Malchor's Leap.
        { "[&BKYCAAA=]", "Pagga's Waypoint" },
        { "[&BKcCAAA=]", "Doric's Waypoint" },
        { "[&BKgCAAA=]", "Waste Hollows Waypoint" },
        { "[&BKkCAAA=]", "Colonnade Waypoint" },
        { "[&BKoCAAA=]", "Valley of Lyss Waypoint" },
        { "[&BKsCAAA=]", "Union Waypoint" },
        { "[&BKwCAAA=]", "Wren Waypoint" },
        { "[&BK0CAAA=]", "Lyssa Waypoint" },
        { "[&BK4CAAA=]", "Blighted Arch Waypoint" },
        { "[&BK8CAAA=]", "Murmur Waypoint" },
        { "[&BLACAAA=]", "Tempest Waypoint" },
        { "[&BLECAAA=]", "Versoconjouring Waypoint" },
        { "[&BLICAAA=]", "Lights Waypoint" },

        // Straits of Devastation.
        { "[&BOwCAAA=]", "Bramble Pass Waypoint" },
        { "[&BO0CAAA=]", "Signal Peak Waypoint" },
        { "[&BO4CAAA=]", "Fort Trinity Waypoint" },
        { "[&BO8CAAA=]", "Thorn Pass Waypoint" },
        { "[&BPACAAA=]", "Thunderhead Waypoint" },
        { "[&BPECAAA=]", "Broken Spit Waypoint" },
        { "[&BPICAAA=]", "Vesper Bell Waypoint" },
        { "[&BPMCAAA=]", "Royal Forum Waypoint" },
        { "[&BPQCAAA=]", "Brassclaw Waypoint" },
        { "[&BPUCAAA=]", "Antheneum Waypoint" },
        { "[&BPYCAAA=]", "Conquest Marina Waypoint" },
        { "[&BPcCAAA=]", "Lone Post Waypoint" },
        { "[&BPgCAAA=]", "Waywarde Waypoint" },
        { "[&BPkCAAA=]", "Xenarius Waypoint" },
        { "[&BPoCAAA=]", "Glorious Victory Waypoint" },
        { "[&BPsCAAA=]", "Sentry Waypoint" },
        { "[&BNIEAAA=]", "Rally Waypoint" },
        { "[&BFgGAAA=]", "Plinth Timberland Waypoint" },
        { "[&BFkGAAA=]", "Underbelly Waypoint" },
        { "[&BOUGAAA=]", "Dire Shoal Waypoint" },

        // Sea of Sorrows.
        // Southsun Cove.
        { "[&BNAGAAA=]", "Lion Point Waypoint" },
        { "[&BNIGAAA=]", "Pride Point Waypoint" },
        { "[&BNUGAAA=]", "Pearl Islet Waypoint" },
        { "[&BNcGAAA=]", "Camp Karka Waypoint" },
        { "[&BNgGAAA=]", "Owain's Refuge Waypoint" },
        { "[&BNwGAAA=]", "Kiel's Outpost Waypoint " },

        // Shiverpeak Mountains.
        // Dredgehaunt Cliffs.
        { "[&BFYCAAA=]", "Tribulation Waypoint" },
        { "[&BFcCAAA=]", "Frostland Waypoint" },
        { "[&BFgCAAA=]", "Dociu Waypoint" },
        { "[&BFkCAAA=]", "Seven Pines Waypoint" },
        { "[&BFoCAAA=]", "Grey Road Waypoint" },
        { "[&BFsCAAA=]", "Steelbrachen Waypoint" },
        { "[&BFwCAAA=]", "Toran Hollow Waypoint" },
        { "[&BF0CAAA=]", "Hessdallen Kenning Waypoint" },
        { "[&BF4CAAA=]", "Kenning Testing Ground Waypoint" },
        { "[&BF8CAAA=]", "Wide Expanse Waypoint" },
        { "[&BGACAAA=]", "Nottowr Fault Waypoint" },
        { "[&BGECAAA=]", "Mountain's Tail Waypoint" },
        { "[&BGICAAA=]", "Graupel Waypoint" },
        { "[&BGMCAAA=]", "Havfrue Basin Waypoint" },
        { "[&BGQCAAA=]", "Travelen's Waypoint" },
        { "[&BGUCAAA=]", "Wyrmblood Waypoint" },
        { "[&BO4EAAA=]", "Granite Citadel Waypoint" },
        { "[&BD8FAAA=]", "Sorrow's Embrace Waypoint " },

        // Frostgorge Sound.
        { "[&BHgCAAA=]", "Arundon Waypoint" },
        { "[&BHkCAAA=]", "Groznev Waypoint" },
        { "[&BHoCAAA=]", "Earthshake Waypoint" },
        { "[&BHsCAAA=]", "Path of Starry Skies Waypoint" },
        { "[&BHwCAAA=]", "Slough of Despond Waypoint" },
        { "[&BH0CAAA=]", "Watchful Waypoint" },
        { "[&BH4CAAA=]", "Ice Floe Waypoint" },
        { "[&BH8CAAA=]", "Dimotiki Waypoint" },
        { "[&BIACAAA=]", "Twoloop Waypoint" },
        { "[&BIECAAA=]", "Skyheight Steading Waypoint" },
        { "[&BIICAAA=]", "Highpeaks Waypoint" },
        { "[&BIMCAAA=]", "Ridgerock Camp Waypoint" },
        { "[&BIQCAAA=]", "Yak's Bend Waypoint" },
        { "[&BIUCAAA=]", "Blue Ice Shining Waypoint" },
        { "[&BIYCAAA=]", "Drakkar Waypoint" },
        { "[&BEMFAAA=]", "Honor of the Waves Waypoint" },

        // Lornar's Pass.
        { "[&BOUAAAA=]", "Vanjir's Stead Waypoint" },
        { "[&BOYAAAA=]", "Demon's Maw Waypoint" },
        { "[&BOcAAAA=]", "Winterthaw Waypoint" },
        { "[&BOgAAAA=]", "False Lake Waypoint" },
        { "[&BOkAAAA=]", "Durmand Priory Waypoint" },
        { "[&BOoAAAA=]", "Lamentation Waypoint" },
        { "[&BOsAAAA=]", "Thunderhorns Waypoint" },
        { "[&BOwAAAA=]", "Nentor Waypoint" },
        { "[&BJYBAAA=]", "Guutra's Homestead Waypoint" },
        { "[&BJcBAAA=]", "Stonescatter Waypoint" },
        { "[&BJgBAAA=]", "Pinnacle Enclave Waypoint" },
        { "[&BJkBAAA=]", "Mistriven Waypoint" },
        { "[&BFEGAAA=]", "Icedevil's Waypoint" },
        { "[&BFIGAAA=]", "Refuge Peak Waypoint" },
        { "[&BFMGAAA=]", "Afgar's Waypoint" },
        { "[&BFQGAAA=]", "Cascade Bridge Waypoint" },
        { "[&BDEHAAA=]", "False River Waypoint" },

        // Snowden Drifts.
        { "[&BLMAAAA=]", "Skradden Waypoint" },
        { "[&BLQAAAA=]", "Lornar's Waypoint" },
        { "[&BLUAAAA=]", "Highpass Haven Waypoint" },
        { "[&BLYAAAA=]", "Lost Child's Sorrow Waypoint" },
        { "[&BLcAAAA=]", "Scholar's Cleft Waypoint" },
        { "[&BLgAAAA=]", "Isenfall Waypoint" },
        { "[&BLkAAAA=]", "Snowdrift Haven Waypoint" },
        { "[&BLoAAAA=]", "Seraph Outriders' Waypoint" },
        { "[&BLsAAAA=]", "Torstvedt Homestead Waypoint" },
        { "[&BLwAAAA=]", "Exile Waypoint" },
        { "[&BL0AAAA=]", "Njordstead Waypoint" },
        { "[&BL4AAAA=]", "Soderhem Steading Waypoint" },
        { "[&BL8AAAA=]", "Snowhawk Landing Waypoint" },
        { "[&BMAAAAA=]", "Reaver's Waypoint" },
        { "[&BMEAAAA=]", "Owl Waypoint" },
        { "[&BMIAAAA=]", "Podaga Steading Waypoint" },
        { "[&BL8DAAA=]", "Frozen Sweeps Waypoint" },
        { "[&BMADAAA=]", "Valslake Waypoint" },
        { "[&BP8GAAA=]", "Angvar's Trove Waypoint " },

        // Timberline Falls.
        { "[&BEQCAAA=]", "Talus Waypoint" },
        { "[&BEUCAAA=]", "Serpent Waypoint" },
        { "[&BEYCAAA=]", "Okarinoo Waypoint" },
        { "[&BEcCAAA=]", "Coil Waypoint" },
        { "[&BEgCAAA=]", "Scale Strand Waypoint" },
        { "[&BEkCAAA=]", "Nonmoa Waypoint" },
        { "[&BEoCAAA=]", "Eztlitl Grounds Waypoint" },
        { "[&BEsCAAA=]", "Gyre Rapids Waypoint" },
        { "[&BEwCAAA=]", "Valance Tutory Waypoint" },
        { "[&BE0CAAA=]", "Ogduk Waypoint" },
        { "[&BE4CAAA=]", "Foundation 86 Waypoint" },
        { "[&BE8CAAA=]", "White Paper Waypoint" },
        { "[&BFACAAA=]", "Gentle River Waypoint" },
        { "[&BFECAAA=]", "Thistlereed Waypoint" },
        { "[&BFICAAA=]", "Krongar Waypoint" },
        { "[&BFMCAAA=]", "Iron Veil Waypoint" },
        { "[&BFQCAAA=]", "Rankor Ruins Waypoint" },
        { "[&BFUCAAA=]", "Concordia Waypoint" },
        { "[&BEYEAAA=]", "Stromkarl Waypoint" },

        // Wayfarer Foothills.
        { "[&BHIBAAA=]", "Outcast's Waypoint" },
        { "[&BHMBAAA=]", "Hero's Moot Waypoint" },
        { "[&BHQBAAA=]", "Horncall Waypoint" },
        { "[&BHUBAAA=]", "Darkriven Waypoint" },
        { "[&BHYBAAA=]", "Taigan Waypoint" },
        { "[&BHcBAAA=]", "Zelechor Hot Springs Waypoint" },
        { "[&BHgBAAA=]", "Halvaunt Waypoint" },
        { "[&BHkBAAA=]", "Crossroads Haven Waypoint" },
        { "[&BHoBAAA=]", "Dawnrise Waypoint" },
        { "[&BHsBAAA=]", "Dolyak Pass Waypoint" },
        { "[&BHwBAAA=]", "Solitude Waypoint" },
        { "[&BH0BAAA=]", "Twinspur Haven Waypoint" },
        { "[&BH4BAAA=]", "Vendrake's Homestead Waypoint" },
        { "[&BMEDAAA=]", "Lostvyrm Cave Waypoint" },
        { "[&BMIDAAA=]", "Krennak's Homestead Waypoint" },
        { "[&BMMDAAA=]", "Grawlenfjord Waypoint" },
        { "[&BAEEAAA=]", "Osenfold Waypoint" },

        // Bitterfrost Frontier.
        { "[&BH0JAAA=]", "Sorrow's Eclipse Waypoint" },
        { "[&BIEJAAA=]", "Koda's Flame Waypoint" },

        // Cities.
        // Black Citadel.
        { "[&BKQDAAA=]", "Gladium Waypoint" },
        { "[&BKUDAAA=]", "Mustering Ground Waypoint" },
        { "[&BKYDAAA=]", "Memorial Waypoint" },
        { "[&BKcDAAA=]", "Factorium Waypoint" },
        { "[&BKgDAAA=]", "Diessa Gate Waypoint" },
        { "[&BKkDAAA=]", "Ligacus Aquilo Waypoint" },
        { "[&BKoDAAA=]", "Bane Waypoint" },
        { "[&BKsDAAA=]", "Hero's Waypoint" },
        { "[&BKwDAAA=]", "Ruins of Rin Waypoint" },
        { "[&BK0DAAA=]", "Imperator's Waypoint" },
        { "[&BDcEAAA=]", "Junker's Waypoint" },
        { "[&BCkHAAA=]", "Haunted Nolani Waypoint" },

        // Divinity's Reach.
        { "[&BCMDAAA=]", "Dwayna Waypoint" },
        { "[&BCQDAAA=]", "Grenth Waypoint" },
        { "[&BCUDAAA=]", "Kormir Waypoint" },
        { "[&BCYDAAA=]", "Lyssa Waypoint" },
        { "[&BCcDAAA=]", "Melandru Waypoint" },
        { "[&BCgDAAA=]", "Balthazar Waypoint" },
        { "[&BCkDAAA=]", "Palace Waypoint" },
        { "[&BCoDAAA=]", "Commons Waypoint" },
        { "[&BCsDAAA=]", "Rurikton Waypoint" },
        { "[&BCwDAAA=]", "Crown Pavilion Waypoint" },
        { "[&BC0DAAA=]", "Ossan Waypoint" },
        { "[&BC4DAAA=]", "Salma Waypoint" },
        { "[&BP4EAAA=]", "Ministers Waypoint" },

        // Hoelbrak.
        { "[&BIUDAAA=]", "Might and Main Waypoint" },
        { "[&BIYDAAA=]", "Trade Commons Waypoint" },
        { "[&BIcDAAA=]", "Snow Leopard Waypoint" },
        { "[&BIgDAAA=]", "Raven Waypoint" },
        { "[&BIkDAAA=]", "Bear Waypoint" },
        { "[&BIoDAAA=]", "Wolf Waypoint" },
        { "[&BIsDAAA=]", "Shelter Rock Waypoint" },
        { "[&BIwDAAA=]", "Legends Waypoint" },
        { "[&BI0DAAA=]", "Eastern Watchpost Waypoint" },
        { "[&BI4DAAA=]", "Southern Watchpost Waypoint" },
        { "[&BI8DAAA=]", "Peeta's Waypoint" },
        { "[&BJADAAA=]", "Hero's Compass Waypoint" },
        { "[&BNUDAAA=]", "Great Lodge Waypoint" },
        { "[&BAgFAAA=]", "Upper Balcony Waypoint" },

        // Lion's Arch.
        { "[&BAwEAAA=]", "Commodore's Quarter Waypoint" },
        { "[&BA0EAAA=]", "Guild Bluff Waypoint" },
        { "[&BA4EAAA=]", "Bloodcoast Ward Waypoint" },
        { "[&BA8EAAA=]", "Claw Island Portage Waypoint" },
        { "[&BBAEAAA=]", "Trader's Forum Waypoint" },
        { "[&BBEEAAA=]", "Gate Hub Plaza Waypoint" },
        { "[&BC0EAAA=]", "Diverse Ledges Waypoint" },
        { "[&BC4EAAA=]", "Western Ward Waypoint" },
        { "[&BC8EAAA=]", "Sanctum Harbor Waypoint" },
        { "[&BDAEAAA=]", "Fort Marriner Waypoint" },
        { "[&BDEEAAA=]", "Eastern Ward Waypoint" },
        { "[&BDIEAAA=]", "Cavern Waypoint" },
        { "[&BDMEAAA=]", "Farshore Waypoint" },

        // Rata Sum.
        { "[&BBMEAAA=]", "Metrical Court Waypoint" },
        { "[&BBQEAAA=]", "Magustan Court Waypoint" },
        { "[&BLQEAAA=]", "Magicat Court Waypoint" },
        { "[&BLUEAAA=]", "Incubation Waypoint" },
        { "[&BLYEAAA=]", "Accountancy Waypoint" },
        { "[&BLcEAAA=]", "Apprentice Waypoint" },
        { "[&BLgEAAA=]", "Research Waypoint" },
        { "[&BLkEAAA=]", "Auxiliary Waypoint" },
        { "[&BAcFAAA=]", "Port Waypoint" },

        // The Grove.
        { "[&BBIEAAA=]", "Caledon Waypoint" },
        { "[&BLoEAAA=]", "Upper Commons Waypoint" },
        { "[&BLsEAAA=]", "Reckoner's Waypoint" },
        { "[&BLwEAAA=]", "Ronan's Waypoint " },
    };
}